# Generated by Django 4.0 on 2021-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('sensor_reading', models.FloatField()),
                ('sensor_tick', models.IntegerField()),
            ],
        ),
    ]
