# Generated by Django 4.0 on 2021-12-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAS', '0002_reading_db_test_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_report_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('time', models.IntegerField()),
                ('anglex', models.IntegerField()),
                ('angley', models.IntegerField()),
                ('anglez', models.IntegerField()),
            ],
        ),
    ]
