# Generated by Django 4.0 on 2021-12-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAS', '0003_sensor_report_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor_report_db',
            old_name='time',
            new_name='time_s',
        ),
        migrations.AlterField(
            model_name='sensor_report_db',
            name='anglex',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor_report_db',
            name='angley',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor_report_db',
            name='anglez',
            field=models.FloatField(),
        ),
    ]
