# Generated by Django 4.0 on 2021-12-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DAS', '0004_rename_time_sensor_report_db_time_s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor_report_db',
            name='status',
        ),
    ]
