# Generated by Django 4.0 on 2021-12-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAS', '0006_sensor_report_db_message_sensor_report_db_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_control_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('stat', models.IntegerField()),
            ],
        ),
    ]
