# Generated by Django 4.0 on 2021-12-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DAS', '0007_test_control_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_control_db',
            old_name='name',
            new_name='ctrl_name',
        ),
        migrations.RenameField(
            model_name='test_control_db',
            old_name='stat',
            new_name='ctrl_stat',
        ),
    ]
